# Generated by Django 6.0.6 on 2026-06-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='phone number')),
                ('random_code', models.SmallIntegerField(verbose_name='random code')),
                ('expriy_date', models.DateField(verbose_name='expriy date')),
            ],
        ),
    ]
