# Generated by Django 6.0.6 on 2026-06-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expriy_date',
            field=models.DateField(auto_now_add=True, verbose_name='expriy date'),
        ),
    ]
