# Generated by Django 6.0.6 on 2026-06-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='token'),
        ),
    ]
