# Generated by Django 6.0 on 2026-07-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
